.\" Copyright (C) 2016 by Dodlaz
.TH EXTRACT 8 "2016" Linux "User Manuals"
.SH NAME
extract \- extracts files and directorys from compressed files

.SH SYNOPSIS
.B extract
.I FILE
.B . [
.I tar.bz2
.B |
.I tar.gz
.B |
.I tar.xz
.B |
.I bz2
.B |
.I rar
.B |
.I gz
.B |
.I tar
.B |
.I tbz2
.B |
.I tgz
.B |
.I zip
.B |
.I Z
.B |
.I 7z
.B ]

.SH DESCRIPTION
.BR extract
runs
.B tar(1), zip(1), bzip2(1), rar(1), gzip(1)
or
.B unzip(1)
to extract the files from the file to curent dir.

.SH EXAMPLES
Unpack the files in the compressd file
.RS
extract images.tar.gz
.RE

.SH AUTHOR
Dodlaz

.SH "SEE ALSO"
tar(1),
zip(1),
rar(1),
gzip(1),
bzip2(1),
unzip(1)
